name: Singularity Build
on: 
  push:

    # This recipe shows how to manually define a matrix of singularity recipes (paths) to build
    # Edit the branches here if you want to change deploy behavior
    branches:
      - master
    tags: 
      - v*

  # Do the builds on all pull requests (to test them)
  pull_request: []
  workflow_dispatch:

jobs:
  build-containers:
    runs-on: ubuntu-latest
    # container:
    #   image: quay.io/singularity/singularity:v3.9.3
    #   options: --security-opt seccomp=unconfined --security-opt systempaths=unconfined
    strategy:
      fail-fast: true

    container:
        image: quay.io/singularity/singularity:v4.1.0
        options: --privileged

    name: Build singularity
    steps:

      - name: Check out code for the container build
        uses: actions/checkout@v4

      - name: Step to get tag name
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV


      - name: Step to get tag name
        if: ${{ startsWith(github.ref, 'refs/heads') && github.ref == 'refs/heads/master' }}
        run: echo "tag=latest" >> $GITHUB_ENV
      
      - name: Step to get tag name
        if: ${{ startsWith(github.ref, 'refs/heads') && github.ref != 'refs/heads/master' }}
        run: echo "tag=test" >> $GITHUB_ENV
      
      - name: Build Container
        run: |
          ls ${SINGULARITY_ROOT}
          singularity build wrf-spack-gcc.sif def_files/wrf-spack-gcc.def

      - name: Post build check files
        run: ls

      - name: Login and Deploy Container
        if: (github.event_name != 'pull_request')
        run: |         
          echo ${{ secrets.GITHUB_TOKEN }} | singularity registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push wrf-spack-gcc.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
